server:
  port: 8050

spring:
  application:
    name: camel-microservice-b
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true

camel:
  component:
    kafka:
      brokers: localhost:9092